# Generated by Django 4.2.11 on 2024-04-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_authors_book_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
