# Generated by Django 4.2.11 on 2024-05-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_review_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
