# Generated by Django 4.2.11 on 2024-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnailURL',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='images/review'),
        ),
    ]
